---
platform: linux
image_resource:
  type: docker-image
  source: { repository: ghcr.io/cloudfoundry/bosh/s3cli }
inputs:
- name: bosh-s3cli
- name: version-semver
outputs:
- name: out
run:
  path: bosh-s3cli/ci/tasks/build.sh
params:
  GOOS: linux
