---
platform: linux
image_resource:
  type: docker-image
  source: { repository: ghcr.io/cloudfoundry/bosh/s3cli }
inputs:
- name: bosh-s3cli
run:
  path: bosh-s3cli/ci/tasks/run-integration-s3-compat.sh
params:
  access_key_id:
  secret_access_key:
  bucket_name:
  s3_endpoint_host:
  s3_endpoint_port:
