---
platform: linux
image_resource:
  type: docker-image
  source: { repository: ghcr.io/cloudfoundry/bosh/s3cli }
inputs:
- name: bosh-s3cli
run:
  path: bosh-s3cli/ci/tasks/run-integration-aws-assume.sh
params:
  access_key_id:
  secret_access_key:
  focus_regex:
  s3_endpoint_host:
  assume_role_arn:
