---
platform: linux
image_resource:
  type: docker-image
  source: { repository: ghcr.io/cloudfoundry/bosh-s3cli }
inputs:
- name: bosh-s3cli
run:
  path: bosh-s3cli/ci/tasks/teardown-infrastructure.sh
params:
  access_key_id:
  secret_access_key:
  region_name:
  stack_name:
